[features]
seeds = true
skip-lint = false

[programs.devnet]
mythos = "FGG8363rUtdVernzHtXr4AD9PS9m4BezgAN8MJKcybpM"

[programs.localnet]
mythos = "FGG8363rUtdVernzHtXr4AD9PS9m4BezgAN8MJKcybpM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "C:/Users/Lenovo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/mythos"]
